GET http://localhost:3000/

###

GET http://localhost:3000/cities

###

GET http://localhost:3000/cities/70140

###

GET http://localhost:3000/cities/78787

###

GET http://localhost:3000/cities/abc

###

DELETE http://localhost:3000/cities/25000

###

DELETE http://localhost:3000/cities/abc

###

POST http://localhost:3000/cities
Content-Type: application/json

{
  "zipCode": "70140",
  "name": "Valay"
}